version: '2.4'
services:
  postgres:
    container_name: postgres
    restart: always
    image: eg_postgresql
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432